project:
  type: website


website:
  title: "Training"
  navbar:
    background: "#764ba2"
    foreground: "black"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Courses"
        menu:
          - text: "Web Development"
            href: courses/webdev.qmd
          - text: "Data Science"
            href: courses/datasci.qmd
          - text: "Design"
            href: courses/design.qmd
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/yourrepo
      - icon: twitter
        href: https://twitter.com/yourprofile



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual


